"""
parts of this file were generated by `django-admin startproject` (Django 2.0.3).
"""
import configparser
import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, 'etc', 'django-secret.key')) as fp:
    SECRET_KEY = fp.read()

with open(os.path.join(BASE_DIR, 'etc', 'config')) as fp:
    CONFIG = configparser.ConfigParser()
    CONFIG.read_file(fp)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [CONFIG['site']['Domain']]

INTERNAL_IPS = ['127.0.0.1']
if DEBUG:
    ALLOWED_HOSTS += INTERNAL_IPS

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'acarbroker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.PersistentRemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE

ROOT_URLCONF = 'acarbroker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acarbroker.wsgi.application'


if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'acbdb',
            'USER': 'acb',
            'HOST': '127.0.0.1',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

with open(os.path.join(BASE_DIR, 'etc', 'auth0-clientid.key')) as fp:
    AUTH0_CLIENT_ID = fp.read()
# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, 'etc', 'auth0-secret.key')) as fp:
    AUTH0_CLIENT_SECRET = fp.read()

AUTH0_TENANT_DOMAIN = CONFIG['site']['Auth0TenantDomain']

if DEBUG:
    AUTH0_REDIRECT_URI = 'http://127.0.0.1:8000/complete/auth0'
else:
    AUTH0_REDIRECT_URI = 'https://{}/complete/auth0'.format(CONFIG['site']['Domain'])

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'acarbroker.User'


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_to_deploy')
