"""
parts of this file were generated by `django-admin startproject` (Django 2.0.3).
"""
import os

from django.core.wsgi import get_wsgi_application


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "acarbroker.settings")

application = get_wsgi_application()
